#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- Home: 'index.md'
- API:
  - Getting Started: 'API/Users_Guide/Getting_Started.md'
  - Search and Retrieval: 'API/Users_Guide/Search_and_Retrieval.md'
  - Downloading Files: 'API/Users_Guide/Downloading_Files.md'
  - BAM Slicing: 'API/Users_Guide/BAM_Slicing.md'
  - Submission: 'API/Users_Guide/Submission.md'
  - System Information: 'API/Users_Guide/System_Information.md'
  - Additional Examples: 'API/Users_Guide/Additional_Examples.md'
  - "Appendix A: Available Fields": 'API/Users_Guide/Appendix_A_Available_Fields.md'
  - "Appendix B: Key Terms": 'API/Users_Guide/Appendix_B_Key_Terms.md'
  - "Appendix C: Format of Submission Queries and Responses": 'API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md'
  - Release Notes: 'API/Release_Notes/API_Release_Notes.md'
  - fa-file-text Download PDF /API/PDF/API_UG.pdf: 'API/PDF/index.md'
- Data Portal:
  - Getting Started: 'Data_Portal/Users_Guide/Getting_Started.md'
  - Authentication: 'Data_Portal/Users_Guide/Authentication.md'
  - Features: 'Data_Portal/Users_Guide/Features.md'
  - Projects: 'Data_Portal/Users_Guide/Projects.md'
  - Data: 'Data_Portal/Users_Guide/Data.md'
  - BAM Slicing: 'Data_Portal/Users_Guide/BAM_Slicing.md'
  - Annotations: 'Data_Portal/Users_Guide/Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/Advanced_Search.md'
  - Reports: 'Data_Portal/Users_Guide/Reports.md'
  - Cart and Files Download: 'Data_Portal/Users_Guide/Cart.md'
  - Legacy Archive: 'Data_Portal/Users_Guide/Legacy_Archive.md'
  - Key Terms: 'Data_Portal/Users_Guide/Key_Terms.md'
  - Release Notes: 'Data_Portal/Release_Notes/Data_Portal_Release_Notes.md'
  - fa-file-text Download PDF /Data_Portal/PDF/Data_Portal_UG.pdf: 'Data_Portal/PDF/index.md'
- Data Submission Portal:
  - Getting Started: 'Data_Submission_Portal/Users_Guide/Getting_Started.md'
  - Submission Workflow: 'Data_Submission_Portal/Users_Guide/Submission_Workflow.md'
  - Authentication: 'Data_Submission_Portal/Users_Guide/Authentication.md'
  - Homepage: 'Data_Submission_Portal/Users_Guide/Homepage.md'
  - Dashboard: 'Data_Submission_Portal/Users_Guide/Dashboard.md'
  - Upload and Validate Data: 'Data_Submission_Portal/Users_Guide/Upload_Data.md'
  - Submit Data: 'Data_Submission_Portal/Users_Guide/Submit_Data.md'
  - Release Data: 'Data_Submission_Portal/Users_Guide/Release_Data.md'
  - Transactions: 'Data_Submission_Portal/Users_Guide/Transactions.md'
  - Browse Data: 'Data_Submission_Portal/Users_Guide/Browse_Data.md'
  - Submission Examples: 'Data_Submission_Portal/Users_Guide/Examples.md'
  - Release Notes: 'Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md'
  - fa-file-text Download PDF /Data_Submission_Portal/PDF/Data_Submission_Portal_UG.pdf: 'Data_Submission_Portal/PDF/index.md'
- Data Transfer Tool:
  - Getting Started: 'Data_Transfer_Tool/Users_Guide/Getting_Started.md'
  - Accessing Built-in Help: 'Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md'
  - Preparing for Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md'
  - Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md'
  - Key Terms: 'Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md'
  - Release Notes: 'Data_Transfer_Tool/Release_Notes/DTT_Release_Notes.md'
  - fa-file-text Download PDF /Data_Transfer_Tool/PDF/Data_Transfer_Tool_UG.pdf: 'Data_Transfer_Tool/PDF/index.md'
- Data Dictionary:
  - About: 'Data_Dictionary/index.md'
  - Viewer: 'Data_Dictionary/viewer.md'
- Data:
  - Introduction: 'Data/Introduction.md'
  - GDC Data Model: 'Data/Data_Model/GDC_Data_Model.md'
  - Data Security: 'Data/Data_Security/Data_Security.md'
  - "File Format: MAF": 'Data/File_Formats/MAF_Format.md'
  - "File Format: VCF": 'Data/File_Formats/VCF_Format.md'
  - "Bioinformatics Pipeline: miRNA Analysis": 'Data/Bioinformatics_Pipelines/miRNA_Pipeline.md'
  - "Bioinformatics Pipeline: mRNA Analysis": 'Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md'
  - "Bioinformatics Pipeline: DNA-Seq Analysis": 'Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline.md'
  - "Bioinformatics Pipeline: Copy Number Variation Analysis": 'Data/Bioinformatics_Pipelines/CNV_Pipeline.md'
  - "Release Notes": 'Data/Release_Notes/Data_Release_Notes.md'
  - fa-file-text Download PDF /Data/PDF/Data_UG.pdf: 'Data/PDF/index.md'
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
  dictionary_viewer_page_id: 'Viewer'
  dictionary_app_root: '/apps/dictionary'
markdown_extensions:
  - BSCodeTabExtension:
      default_lang: 'Source'
      show_all_code_as_folders: True
      animate_tab_transitions: False
