copyright: '&copy; 2015-2016'
extra:
  dictionary_app_root: /apps/dictionary
  dictionary_viewer_page_id: Viewer
  encyclopedia_entries_page_title: EncyclopediaEntries
  encyclopedia_page_title: Encyclopedia
  nav_exclude:
  - EncyclopediaEntries
  project_description: GDC Docs
  project_org: GDC
  project_root_dir: /
  version: 1.0
extra_css:
- css/encyclopedia.css
markdown_extensions:
- tables
- BSCodeTabExtension:
    animate_tab_transitions: false
    default_lang: Source
    show_all_code_as_folders: true
pages:
- Home: index.md
- API:
  - Getting Started: API/Users_Guide/Getting_Started.md
  - Search and Retrieval: API/Users_Guide/Search_and_Retrieval.md
  - Downloading Files: API/Users_Guide/Downloading_Files.md
  - Data Analysis: API/Users_Guide/Data_Analysis.md
  - BAM Slicing: API/Users_Guide/BAM_Slicing.md
  - Submission: API/Users_Guide/Submission.md
  - System Information: API/Users_Guide/System_Information.md
  - Additional Examples: API/Users_Guide/Additional_Examples.md
  - 'Appendix A: Available Fields': API/Users_Guide/Appendix_A_Available_Fields.md
  - 'Appendix B: Key Terms': API/Users_Guide/Appendix_B_Key_Terms.md
  - 'Appendix C: Format of Submission Queries and Responses': API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md
  - Release Notes: API/Release_Notes/API_Release_Notes.md
  - fa-file-text Download PDF /API/PDF/API_UG.pdf: API/PDF/index.md
- Data Portal:
  - Getting Started: Data_Portal/Users_Guide/Getting_Started.md
  - Projects: Data_Portal/Users_Guide/Projects.md
  - Exploration: Data_Portal/Users_Guide/Exploration.md
  - Repository: Data_Portal/Users_Guide/Repository.md
  - Genes and Mutations: Data_Portal/Users_Guide/Genes_and_Mutations.md
  - Annotations: Data_Portal/Users_Guide/Annotations.md
  - Advanced Search: Data_Portal/Users_Guide/Advanced_Search.md
  - Authentication: Data_Portal/Users_Guide/Authentication.md
  - Downloading Files: Data_Portal/Users_Guide/Cart.md
  - Legacy Archive: Data_Portal/Users_Guide/Legacy_Archive.md
  - Release Notes: Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
  - fa-file-text Download PDF /Data_Portal/PDF/Data_Portal_UG.pdf: Data_Portal/PDF/index.md
- Data Submission Portal:
  - Getting Started: Data_Submission_Portal/Users_Guide/Getting_Started.md
  - Submission Workflow: Data_Submission_Portal/Users_Guide/Submission_Workflow.md
  - Authentication: Data_Submission_Portal/Users_Guide/Authentication.md
  - Homepage: Data_Submission_Portal/Users_Guide/Homepage.md
  - Dashboard: Data_Submission_Portal/Users_Guide/Dashboard.md
  - Upload Data: Data_Submission_Portal/Users_Guide/Data_Upload_UG.md
  - Submit Data: Data_Submission_Portal/Users_Guide/Submit_Data.md
  - Release Data: Data_Submission_Portal/Users_Guide/Release_Data.md
  - Transactions: Data_Submission_Portal/Users_Guide/Transactions.md
  - Browse Data: Data_Submission_Portal/Users_Guide/Browse_Data.md
  - Best Practices: Data_Submission_Portal/Users_Guide/Best_Practices.md
  - Release Notes: Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md
  - fa-file-text Download PDF /Data_Submission_Portal/PDF/Data_Submission_Portal_UG.pdf: Data_Submission_Portal/PDF/index.md
- Data Transfer Tool:
  - Getting Started: Data_Transfer_Tool/Users_Guide/Getting_Started.md
  - Accessing Built-in Help: Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md
  - Preparing for Data Download and Upload: Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md
  - Data Download and Upload: Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md
  - Key Terms: Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md
  - Release Notes: Data_Transfer_Tool/Release_Notes/DTT_Release_Notes.md
  - fa-file-text Download PDF /Data_Transfer_Tool/PDF/Data_Transfer_Tool_UG.pdf: Data_Transfer_Tool/PDF/index.md
- Data Dictionary:
  - About: Data_Dictionary/index.md
  - Viewer: Data_Dictionary/viewer.md
- Data:
  - Introduction: Data/Introduction.md
  - GDC Data Model: Data/Data_Model/GDC_Data_Model.md
  - Data Security: Data/Data_Security/Data_Security.md
  - 'File Format: MAF': Data/File_Formats/MAF_Format.md
  - 'File Format: VCF': Data/File_Formats/VCF_Format.md
  - 'Bioinformatics Pipeline: DNA-Seq Analysis': Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline.md
  - 'Bioinformatics Pipeline: mRNA Analysis': Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md
  - 'Bioinformatics Pipeline: miRNA Analysis': Data/Bioinformatics_Pipelines/miRNA_Pipeline.md
  - 'Bioinformatics Pipeline: Copy Number Variation Analysis': Data/Bioinformatics_Pipelines/CNV_Pipeline.md
  - 'Bioinformatics Pipeline: Methylation Liftover Pipeline': Data/Bioinformatics_Pipelines/Methylation_LO_Pipeline.md
  - Release Notes: Data/Release_Notes/Data_Release_Notes.md
  - fa-file-text Download PDF /Data/PDF/Data_UG.pdf: Data/PDF/index.md
- Encyclopedia: Encyclopedia/index.md
- EncyclopediaEntries:
  - Biospecimen Data: Encyclopedia/pages/Biospecimen_Data.md
  - Case: Encyclopedia/pages/Case.md
  - Center for Cancer Genomics: Encyclopedia/pages/Center_for_Cancer_Genomics.md
  - Clinical Data: Encyclopedia/pages/Clinical_Data.md
  - Clinical Supplement: Encyclopedia/pages/Clinical_Supplement.md
  - Controlled Access: Encyclopedia/pages/Controlled_Access.md
  - Data Submitter: Encyclopedia/pages/Data_Submitter.md
  - dbGaP: Encyclopedia/pages/dbGaP.md
  - Entity: Encyclopedia/pages/Entity.md
  - GDC API: Encyclopedia/pages/GDC_API.md
  - GDC cBioPortal: Encyclopedia/pages/GDC_cBioPortal.md
  - GDC Data Portal: Encyclopedia/pages/GDC_Data_Portal.md
  - GDC Data Submission Portal: Encyclopedia/pages/GDC_Data_Submission_Portal.md
  - GDC Data Transfer Tool: Encyclopedia/pages/GDC_Data_Transfer_Tool.md
  - GDC Documentation Site: Encyclopedia/pages/GDC_Documentation_Site.md
  - GDC Web Site: Encyclopedia/pages/GDC_Web_Site.md
  - Genomic Data Commons: Encyclopedia/pages/Genomic_Data_Commons.md
  - Harmonized Data: Encyclopedia/pages/Harmonized_Data.md
  - HTSeq-Counts: Encyclopedia/pages/HTSeq-Counts.md
  - HTSeq-FPKM-UQ: Encyclopedia/pages/HTSeq-FPKM-UQ.md
  - HTSeq-FPKM: Encyclopedia/pages/HTSeq-FPKM.md
  - Latest Data: Encyclopedia/pages/Latest_Data.md
  - Manifest File: Encyclopedia/pages/Manifest_File.md
  - Mutation Annotation Format: Encyclopedia/pages/Mutation_Annotation_Format.md
  - Redaction: Encyclopedia/pages/Redaction.md
  - Release Number: Encyclopedia/pages/Release_Number.md
  - REST API: Encyclopedia/pages/REST_API.md
  - RNA-Seq: Encyclopedia/pages/RNA-Seq.md
  - SNP Array-Based Data: Encyclopedia/pages/SNP_Array-Based_Data.md
  - UUID: Encyclopedia/pages/UUID.md
  - Variant Call Format: Encyclopedia/pages/Variant_Call_Format.md
  - Variant Type: Encyclopedia/pages/Variant_Type.md
repo_url: https://github.com/NCI-GDC/gdc-docs
site_name: GDC Docs
site_url: http://docs.gdc.cancer.gov
theme: mkdocs
theme_dir: theme
